openapi: 3.0.1
info:
  title: CacheAPI
  description: API Definition of CacheAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/cache
paths:
  /:
    get:
      responses:
        default:
          description: Default response
